<?xml version="1.0" ?>
<robot name="striker_bot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="chassis_length" value="1.30"/>
  <xacro:property name="chassis_width" value="0.65"/>
  <xacro:property name="chassis_height" value="0.50"/>
  <xacro:property name="chassis_mass" value="150.0"/>

  <xacro:property name="wheel_radius" value="0.15"/> 
  <xacro:property name="wheel_width" value="0.10"/>
  <xacro:property name="wheel_mass" value="5.0"/>

  <xacro:property name="wheel_separation_length" value="0.77"/> 
  <xacro:property name="wheel_separation_width" value="0.75"/>  
  <xacro:property name="wheel_z_offset" value="-0.15"/>

  <material name="red"><color rgba="0.8 0.0 0.0 1.0"/></material>
  <material name="black"><color rgba="0.0 0.0 0.0 1.0"/></material>
  <material name="dark"><color rgba="0.3 0.3 0.3 1.0"/></material>

  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" 
               iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" 
               izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0.0" ixz="0.0" 
               iyy="${(m/12) * (3*r*r + h*h)}" iyz="0.0" 
               izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius - wheel_z_offset}" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
    </collision>
    <xacro:box_inertia m="${chassis_mass}" w="${chassis_width}" h="${chassis_height}" d="${chassis_length}"/>
  </link>

  <link name="gps_link"/>
  <joint name="gps_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="0.44 0.44 0.06" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <geometry><box size="0.02 0.08 0.02"/></geometry>
      <material name="dark"/>
    </visual>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="camera_link_optical"/>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${x_reflect * wheel_separation_length/2} ${y_reflect * wheel_separation_width/2} ${wheel_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_wheel">
      <mu1>0.1</mu1>
      <mu2>0.1</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <minDepth>0.001</minDepth>
      <maxVel>0.1</maxVel>
      <fdir1>1 0 0</fdir1>
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>

  <gazebo>
    <plugin name="skid_steer_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>
      <update_rate>50</update_rate>
      <num_wheel_pairs>2</num_wheel_pairs>
      
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>

      <wheel_separation>${wheel_separation_width}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>

      <max_wheel_torque>1000</max_wheel_torque>
      <max_wheel_acceleration>5.0</max_wheel_acceleration>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_wheel_joint_state>true</publish_wheel_joint_state>

      <robot_base_frame>base_footprint</robot_base_frame>
      <odometry_frame>odom</odometry_frame>
    </plugin>
  </gazebo>

  <gazebo reference="camera_link">
    <sensor type="camera" name="realsense">
      <update_rate>30.0</update_rate>
      <visualize>true</visualize>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <frame_name>camera_link_optical</frame_name>
      </plugin>
    </sensor>
  </gazebo>
</robot>